name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latestt
    steps:
      - name: print greeting
        run: echo "hello world!"
      - name: print goodbye
        run: echo "g-bye!"
