 name: First workflow
 on: [push, workflow_dispatch]
 jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with: 
          node-version: 18
  deploy: 
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: output github context
        run: echo "${{toJSON(github)}}"
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with: 
          node-version: 18
      - name: Build
        run: npm run build
      - name: deploy
        run: npm echo "deploy...."
